import type { CreativeCapabilities } from "./creative";
import { searchCreatorPool } from "./creator-search";
export type Creator = {
  creative?: CreativeCapabilities;
  avatar?: string;
  banner?: string;
  source?: "sample" | "local";
  availability?: "Available" | "Open to Opportunities" | "Not specified";
  experienceLevel?: "Beginner" | "Intermediate" | "Advanced";
  joinedAt?: string;
  publicPortfolio?: boolean;
  categories?: string[];
  achievementCount?: number;
  id: string;
  name: string;
  username: string;
  identity: string;
  category: string;
  bio: string;
  skills: string[];
  projects: {
    name: string;
    detail: string;
    image?: string;
    video?: string;
    creative?: CreativeCapabilities;
  }[];
  badge: string;
  color: string;
  featured: boolean;
  trending: boolean;
  tags: string[];
};
export const creators: Creator[] = [
  {
    id: "ava-chen",
    name: "Ava Chen",
    username: "avachen",
    identity: "Product Designer",
    category: "Design",
    bio: "Turning complex ideas into thoughtful digital experiences. Exploring the space between design and technology.",
    skills: ["UI/UX", "Figma", "Design systems"],
    projects: [
      {
        name: "Forma",
        detail: "A modular design system for thoughtful products.",
      },
      { name: "Mindful", detail: "A calmer approach to daily planning." },
      { name: "Orbit", detail: "Making creative collaboration feel natural." },
    ],
    badge: "Design storyteller",
    color: "violet",
    featured: true,
    trending: false,
    tags: ["Minimalist", "SaaS"],
  },
  {
    id: "marcus-reed",
    name: "Marcus Reed",
    username: "marcusbuilds",
    identity: "Full-stack Developer",
    category: "Development",
    bio: "Building useful things for the web. Open-source enthusiast with a love for beautiful, accessible interfaces.",
    skills: ["React", "TypeScript", "Node.js"],
    projects: [
      {
        name: "DevSpace",
        detail: "An open workspace for independent developers.",
      },
      { name: "Pulse API", detail: "A lightweight service health monitor." },
    ],
    badge: "Open-source builder",
    color: "blue",
    featured: true,
    trending: true,
    tags: ["Open source", "Web"],
  },
  {
    id: "sana-patel",
    name: "Sana Patel",
    username: "sana.ai",
    identity: "AI Engineer",
    category: "AI & Data",
    bio: "Making machine learning understandable and useful. Curious about human-centered AI and creative tools.",
    skills: ["Python", "Machine learning", "LLMs"],
    projects: [
      { name: "Lens", detail: "An experiment in visual understanding." },
      { name: "Context", detail: "A research assistant prototype." },
      { name: "Signal", detail: "Finding patterns in everyday data." },
    ],
    badge: "AI explorer",
    color: "pink",
    featured: true,
    trending: true,
    tags: ["Research", "AI"],
  },
  {
    id: "leo-martin",
    name: "Leo Martin",
    username: "leomotion",
    identity: "Motion Designer",
    category: "Design",
    bio: "Stories in motion. Creating playful identities and expressive digital experiences.",
    skills: ["Motion", "After Effects", "3D"],
    projects: [{ name: "Fluid", detail: "A motion identity exploration." }],
    badge: "Creative explorer",
    color: "amber",
    featured: false,
    trending: true,
    tags: ["Animation", "Branding"],
  },
  {
    id: "nia-james",
    name: "Nia James",
    username: "niawrites",
    identity: "Content Strategist",
    category: "Writing",
    bio: "Helping good ideas find the right words. Writing about technology, creativity, and the people behind it.",
    skills: ["Writing", "Strategy", "Storytelling"],
    projects: [
      {
        name: "Field Notes",
        detail: "A collection of stories from independent creators.",
      },
      { name: "Plain Words", detail: "A practical content design guide." },
    ],
    badge: "Community voice",
    color: "green",
    featured: false,
    trending: false,
    tags: ["Editorial", "Content"],
  },
  {
    id: "ryan-kim",
    name: "Ryan Kim",
    username: "ryankim",
    identity: "Brand Designer",
    category: "Marketing",
    bio: "Distinct identities for ambitious ideas. A blend of strategy, typography, and a little experimentation.",
    skills: ["Branding", "Art direction", "Strategy"],
    projects: [
      {
        name: "Kin Studio",
        detail: "Identity for an independent creative studio.",
      },
    ],
    badge: "Identity maker",
    color: "violet",
    featured: false,
    trending: false,
    tags: ["Branding", "Creative"],
  },
  // Explicit fictional fixtures, never injected into authenticated user records.
  {
    id: "iman-noor",
    name: "Iman Noor",
    username: "imannotes",
    identity: "Researcher",
    category: "AI & Technology",
    bio: "Exploring how people learn with interactive explanations.",
    skills: ["Python", "Data visualization", "Research"],
    projects: [
      {
        name: "Learning Atlas",
        detail: "An interactive map of learning resources.",
      },
    ],
    badge: "",
    color: "violet",
    featured: false,
    trending: false,
    tags: ["Education", "Research"],
    availability: "Open to Opportunities",
    experienceLevel: "Intermediate",
    joinedAt: "2026-09-28",
    publicPortfolio: true,
  },
  {
    id: "maya-ortiz",
    name: "Maya Ortiz",
    username: "mayateaches",
    identity: "Educator",
    category: "Education",
    bio: "Making programming concepts approachable through small experiments.",
    skills: ["Teaching", "JavaScript", "Writing"],
    projects: [
      {
        name: "Code Garden",
        detail: "A collection of beginner programming exercises.",
      },
    ],
    badge: "",
    color: "pink",
    featured: true,
    trending: false,
    tags: ["Learning", "Programming"],
    availability: "Available",
    experienceLevel: "Intermediate",
    joinedAt: "2026-09-16",
    publicPortfolio: true,
  },
  {
    id: "eli-park",
    name: "Eli Park",
    username: "elilearns",
    identity: "Student",
    category: "Programming",
    bio: "Learning to build accessible tools for everyday tasks.",
    skills: ["HTML", "CSS", "Python"],
    projects: [],
    badge: "",
    color: "violet",
    featured: false,
    trending: false,
    tags: ["Learning", "Accessibility"],
    availability: "Not specified",
    experienceLevel: "Beginner",
    joinedAt: "2026-10-02",
    publicPortfolio: false,
  },
  {
    id: "sam-rivera",
    name: "Sam Rivera",
    username: "sammakes",
    identity: "Founder",
    category: "Programming",
    bio: "Prototyping small tools for independent creative teams.",
    skills: ["Prototyping", "React", "Product strategy"],
    projects: [
      {
        name: "Gather",
        detail: "A prototype for planning team feedback sessions.",
      },
    ],
    badge: "",
    color: "pink",
    featured: false,
    trending: true,
    tags: ["Collaboration", "Tools"],
    availability: "Open to Opportunities",
    joinedAt: "2026-09-21",
    publicPortfolio: true,
  },
  {
    id: "jules-owen",
    name: "Jules Owen",
    username: "julesplays",
    identity: "Content Creator",
    category: "Gaming",
    bio: "Making short explainers about game design and creative play.",
    skills: ["Video editing", "Storytelling", "Game design"],
    projects: [
      { name: "Play Notes", detail: "A series of game-design explainers." },
    ],
    badge: "",
    color: "violet",
    featured: false,
    trending: false,
    tags: ["Video", "Creative play"],
    availability: "Available",
    joinedAt: "2026-09-30",
    publicPortfolio: true,
  },
  {
    id: "ada-lin",
    name: "Ada Lin",
    username: "adacreates",
    identity: "AI Creator",
    category: "AI & Technology",
    bio: "Exploring creative coding and explainable machine learning.",
    skills: ["Python", "Machine learning", "Creative coding"],
    projects: [
      {
        name: "Pattern Studio",
        detail: "A visual playground for exploring generated patterns.",
      },
    ],
    badge: "",
    color: "pink",
    featured: false,
    trending: true,
    tags: ["AI", "Generative art"],
    experienceLevel: "Advanced",
    joinedAt: "2026-10-01",
    publicPortfolio: true,
  },
  {
    id: "demo-zoya-rao",
    name: "Zoya Rao",
    username: "zoyaframes",
    avatar: "/samples/profiles/zoya-rao.jpg",
    banner: "/samples/neon-motorcycle.jpg",
    identity: "AI Filmmaker",
    category: "AI & Data",
    categories: ["AI & Data", "Design", "Marketing"],
    bio: "Fictional demo creator focused on cinematic product films and AI-assisted post-production.",
    skills: ["AI filmmaking", "Art direction", "Video editing", "Compositing"],
    projects: [{
      name: "Afterlight Mobility",
      detail: "Fictional electric-mobility campaign study exploring cinematic product motion and neon environments.",
      image: "/samples/neon-motorcycle.jpg",
      video: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
      creative: {
        specialization: "Cinematic AI product films",
        tools: ["Runway", "After Effects", "DaVinci Resolve"],
        models: ["Gen-3"], contentTypes: ["Product film", "Social video"],
        formats: ["Video", "Campaign cutdown"], aspectRatio: "16:9",
        platforms: ["YouTube", "Instagram"],
        workflow: "Storyboard, generate controlled shots, composite product details, edit and color grade.",
        workflowSteps: ["Storyboard", "Generate", "Composite", "Edit", "Grade"],
        humanContribution: "Creative direction, shot selection, compositing, edit and color grade.",
        sourceAssets: "Fictional product references created for this demo.",
        toolEvidence: ["Demo generation contact sheet"], workflowEvidence: ["Demo shot-to-edit breakdown"],
        pastWorkEvidence: [], commercialUse: "Available", minimumBudget: 1800, currency: "USD",
      },
    }],
    creative: {
      specialization: "Cinematic AI product films", tools: ["Runway", "After Effects", "DaVinci Resolve"], models: ["Gen-3"],
      contentTypes: ["Product film", "Social video"], formats: ["Video", "Campaign cutdown"], aspectRatio: "16:9",
      platforms: ["YouTube", "Instagram"], workflow: "Concept to generated shots, compositing, edit and grade.",
      workflowSteps: ["Concept", "Storyboard", "Generate", "Composite", "Deliver"], humanContribution: "Direction and post-production.", sourceAssets: "Brand product references.",
      toolEvidence: ["Demo generation contact sheet"], workflowEvidence: ["Demo process breakdown"], pastWorkEvidence: [],
      commercialUse: "Available", minimumBudget: 1800, currency: "USD",
    },
    badge: "Sample · AI film", color: "violet", featured: true, trending: true,
    tags: ["Cinematic", "Product", "AI video"], availability: "Available", experienceLevel: "Advanced", publicPortfolio: true, source: "sample",
  },
  {
    id: "demo-mira-sen",
    name: "Mira Sen",
    username: "miragenerative",
    avatar: "/samples/profiles/mira-sen.jpg",
    banner: "/samples/skincare-campaign.jpg",
    identity: "Generative Art Director",
    category: "Design",
    categories: ["Design", "Marketing"],
    bio: "Fictional demo creator producing generative beauty, lifestyle and product campaign visuals.",
    skills: ["Generative art", "Art direction", "Product photography", "Retouching"],
    projects: [{ name: "Tidal Botanics", detail: "Fictional skincare launch study combining studio direction with generative environments.", image: "/samples/skincare-campaign.jpg" }],
    creative: {
      specialization: "Generative beauty campaigns", tools: ["Midjourney", "Photoshop", "ComfyUI"], models: ["SDXL"],
      contentTypes: ["Product image", "Social campaign"], formats: ["Image", "Carousel"], aspectRatio: "4:5",
      platforms: ["Instagram", "Website"], workflow: "Moodboard, controlled generation, product compositing and retouching.",
      workflowSteps: ["Moodboard", "Generate", "Composite", "Retouch"], humanContribution: "Art direction, selection, compositing and final retouch.", sourceAssets: "Fictional packshot and botanical references.",
      toolEvidence: ["Demo node graph"], workflowEvidence: ["Demo layer breakdown"], pastWorkEvidence: [],
      commercialUse: "Available", minimumBudget: 900, currency: "USD",
    },
    badge: "Sample · Generative art", color: "pink", featured: true, trending: true,
    tags: ["Beauty", "Product", "Campaign"], availability: "Open to Opportunities", experienceLevel: "Advanced", publicPortfolio: true, source: "sample",
  },
  {
    id: "demo-arjun-kale",
    name: "Arjun Kale",
    username: "arjunanimates",
    avatar: "/samples/profiles/arjun-kale.jpg",
    banner: "/samples/robot-garden.jpg",
    identity: "AI Animator",
    category: "Design",
    categories: ["Design", "AI & Data"],
    bio: "Fictional demo animator developing character-led explainers and hopeful future-world stories.",
    skills: ["AI animation", "Storyboarding", "Character design", "Sound design"],
    projects: [{ name: "Garden Unit", detail: "Fictional animated short concept about a small robot restoring a rooftop garden.", image: "/samples/robot-garden.jpg", video: "https://media.w3.org/2010/05/sintel/trailer.mp4" }],
    creative: {
      specialization: "AI-assisted character animation", tools: ["Blender", "Runway", "Premiere Pro"], models: ["Gen-3"],
      contentTypes: ["Animation", "Explainer"], formats: ["Video", "Short film"], aspectRatio: "16:9",
      platforms: ["YouTube", "Website"], workflow: "Storyboard, character and environment development, motion generation, edit and sound.",
      workflowSteps: ["Script", "Storyboard", "Design", "Animate", "Sound"], humanContribution: "Story, visual development, animation direction, edit and sound design.", sourceAssets: "Original fictional character and environment concepts.",
      toolEvidence: ["Demo scene setup"], workflowEvidence: ["Demo storyboard progression"], pastWorkEvidence: [],
      commercialUse: "Available", minimumBudget: 1400, currency: "USD",
    },
    badge: "Sample · AI animation", color: "amber", featured: true, trending: false,
    tags: ["Animation", "Character", "Story"], availability: "Available", experienceLevel: "Intermediate", publicPortfolio: true, source: "sample",
  },
  {
    id: "demo-dev-malik",
    name: "Dev Malik",
    username: "devbuildsai",
    identity: "AI Product Developer",
    category: "Development",
    categories: ["Development", "AI & Data"],
    avatar: "/samples/profiles/dev-malik.jpg",
    banner: "/samples/profiles/dev-malik.jpg",
    bio: "Fictional demo developer building reliable AI product prototypes, integrations and internal tools.",
    skills: ["AI integrations", "API engineering", "System design", "Evaluation pipelines"],
    projects: [{ name: "Support Copilot", detail: "Fictional customer-support workspace demonstrating AI integrations, API engineering, retrieval, human review and source citations." }],
    creative: {
      specialization: "AI product development", tools: ["React", "Node.js", "PostgreSQL"], models: ["Gemini"],
      contentTypes: ["Web application", "AI prototype"], formats: ["Responsive web app"], aspectRatio: "Responsive",
      platforms: ["Web"], workflow: "Scope the use case, prototype the workflow, evaluate outputs, add human review and ship measurable iterations.",
      workflowSteps: ["Scope", "Prototype", "Evaluate", "Integrate", "Ship"], humanContribution: "Architecture, implementation, evaluation and production safeguards.", sourceAssets: "Fictional requirements and test cases.",
      toolEvidence: ["Demo architecture map"], workflowEvidence: ["Demo evaluation checklist"], pastWorkEvidence: [],
      commercialUse: "Available", minimumBudget: 2400, currency: "USD",
    },
    badge: "Sample · AI developer", color: "blue", featured: true, trending: false,
    tags: ["AI product", "Full-stack", "Prototype"], availability: "Available", experienceLevel: "Advanced", publicPortfolio: true, source: "sample",
  },
  {
    id: "demo-lena-brooks",
    name: "Lena Brooks",
    username: "lenadelivers",
    identity: "Creative Project Manager",
    category: "Management",
    categories: ["Management", "Marketing"],
    avatar: "/samples/profiles/lena-brooks.jpg",
    banner: "/samples/profiles/lena-brooks.jpg",
    bio: "Fictional demo manager coordinating creative teams, campaign timelines, approvals and delivery.",
    skills: ["Project management", "Creative operations", "Client communication", "Production planning"],
    projects: [{ name: "Launch Control", detail: "Fictional project management and creative operations plan coordinating creators, review rounds, licensing and final delivery." }],
    creative: {
      specialization: "Creative production management", tools: ["Notion", "Asana", "Slack"], models: [],
      contentTypes: ["Campaign operations", "Production plan"], formats: ["Campaign workspace"], aspectRatio: "Not applicable",
      platforms: ["Web", "Social"], workflow: "Translate the brief into milestones, owners, review gates, risk tracking and delivery checks.",
      workflowSteps: ["Brief", "Plan", "Assign", "Review", "Deliver"], humanContribution: "Planning, stakeholder alignment, risk management and quality control.", sourceAssets: "Fictional campaign requirements.",
      toolEvidence: ["Demo production board"], workflowEvidence: ["Demo approval timeline"], pastWorkEvidence: [],
      commercialUse: "Available", minimumBudget: 1200, currency: "USD",
    },
    badge: "Sample · Project manager", color: "violet", featured: true, trending: false,
    tags: ["Operations", "Campaigns", "Delivery"], availability: "Available", experienceLevel: "Advanced", publicPortfolio: true, source: "sample",
  },
  {
    id: "demo-kabir-mehta",
    name: "Kabir Mehta",
    username: "kabirpositions",
    identity: "Brand Strategist",
    category: "Marketing",
    categories: ["Marketing", "Design"],
    avatar: "/samples/profiles/kabir-mehta.jpg",
    banner: "/samples/profiles/kabir-mehta.jpg",
    bio: "Fictional demo strategist helping early-stage brands clarify positioning, voice and campaign direction.",
    skills: ["Brand strategy", "Positioning", "Audience research", "Creative direction"],
    projects: [{ name: "Northstar Rebrand", detail: "Fictional positioning and launch system for a sustainable consumer technology company." }],
    creative: {
      specialization: "Brand positioning and campaign strategy", tools: ["Figma", "Miro", "Notion"], models: [],
      contentTypes: ["Brand strategy", "Campaign concept"], formats: ["Strategy deck", "Creative brief"], aspectRatio: "16:9",
      platforms: ["Website", "Instagram", "LinkedIn"], workflow: "Research the market and audience, define positioning, develop territories and turn the selected direction into a usable brief.",
      workflowSteps: ["Research", "Position", "Explore", "Validate", "Brief"], humanContribution: "Research synthesis, strategic decisions, facilitation and creative direction.", sourceAssets: "Fictional research interviews and category review.",
      toolEvidence: ["Demo positioning canvas"], workflowEvidence: ["Demo decision log"], pastWorkEvidence: [],
      commercialUse: "Available", minimumBudget: 2000, currency: "USD",
    },
    badge: "Sample · Brand strategist", color: "pink", featured: true, trending: true,
    tags: ["Positioning", "Brand", "Research"], availability: "Open to Opportunities", experienceLevel: "Advanced", publicPortfolio: true, source: "sample",
  },
  {
    id: "demo-sofia-alvarez",
    name: "Sofia Alvarez",
    username: "sofiacreates",
    identity: "Content Creator",
    category: "Marketing",
    categories: ["Marketing", "Writing", "Design"],
    avatar: "/samples/profiles/sofia-alvarez.jpg",
    banner: "/samples/profiles/sofia-alvarez.jpg",
    bio: "Fictional demo creator producing approachable short-form product stories for social campaigns.",
    skills: ["Short-form video", "UGC", "Scriptwriting", "Video editing"],
    projects: [{ name: "Everyday Reset", detail: "Fictional short-form video and UGC series demonstrating a wellness product through practical daily routines." }],
    creative: {
      specialization: "Short-form branded content", tools: ["CapCut", "Premiere Pro", "Canva"], models: [],
      contentTypes: ["UGC", "Social video", "Product demo"], formats: ["Vertical video", "Reel"], aspectRatio: "9:16",
      platforms: ["Instagram", "TikTok", "YouTube"], workflow: "Turn product benefits into hooks, scripts and shot lists, then film, edit, caption and prepare platform cutdowns.",
      workflowSteps: ["Research", "Script", "Film", "Edit", "Deliver"], humanContribution: "On-camera performance, scripting, filming, editing and revisions.", sourceAssets: "Fictional product brief and demo props.",
      toolEvidence: ["Demo edit timeline"], workflowEvidence: ["Demo script-to-cut breakdown"], pastWorkEvidence: [],
      commercialUse: "Available", minimumBudget: 650, currency: "USD",
    },
    badge: "Sample · Content creator", color: "amber", featured: true, trending: true,
    tags: ["UGC", "Social", "Lifestyle"], availability: "Available", experienceLevel: "Intermediate", publicPortfolio: true, source: "sample",
  },
];
export const categories = [
  "All creators",
  "Design",
  "Development",
  "AI & Data",
  "Writing",
  "Marketing",
];
export const modes = [
  "AI Chat",
  "Profile Analysis",
  "Project Analysis",
  "Skill Analysis",
  "Achievement Analysis",
  "Creator Identity",
  "Portfolio Improvements",
  "Career Insights",
  "Match Analyzer",
  "Workload Analyzer",
];
export const sectionTypes = [
  "Hero",
  "About",
  "Skills",
  "Projects",
  "Experience",
  "Education",
  "Achievements",
  "Contact",
  "GitHub",
  "LinkedIn",
];
export const premiumFeatures = [
  ["AI Pro", "Deeper conversations and focused creative guidance."],
  [
    "Advanced Analytics",
    "Understand how people discover and engage with your work.",
  ],
  [
    "Premium Portfolio",
    "More ways to express your identity through your portfolio.",
  ],
  [
    "Advanced Matching",
    "Find collaborators with complementary skills and interests.",
  ],
  [
    "Unlimited HECX",
    "More room to explore ideas with your creative assistant.",
  ],
];
export function searchCreators(query: string) {
  return searchCreatorPool(creators, query);
}
