import {ClientSession,Collection} from "mongodb";
import {client} from "../models/database";import {User} from "../models/auth";
import * as m from "../models/marketplace";
import {blankBrand} from "../../lib/mark/marketplace/fixtures";
import {MarketplaceState,Actor,brandSchema,campaignSchema,applicationSchema,invitationSchema} from "../../lib/mark/marketplace/models";
import {brandService,campaignService,applicationService,invitationService,savedCreatorService,toggleSaved,messageService} from "../../lib/mark/marketplace/services";
import {creatorWorkspace,listCreators} from "./creators";import {ownerCreator} from "../../lib/mark/marketplace/matching";
import {notifyChanges} from "./notifications";
import {ApiError} from "../middleware/errors";import {z} from "zod";
export const actorFor=(u:User):Actor=>({signedIn:true,role:u.role,id:u._id});
export async function marketState(user?:User,session?:ClientSession):Promise<MarketplaceState>{const options={session};if(user?.role==="Brand")await m.brands.updateOne({_id:user._id},{$setOnInsert:{data:{...blankBrand,id:user._id}}},{upsert:true,...options});const cs=(await m.campaigns.find({$or:[{"data.status":{$in:["Published","Active","Paused","Completed"]}},...(user?.role==="Brand"?[{"data.brandId":user._id}]:[])]},options).limit(1000).toArray()).map(x=>x.data);const own=cs.filter(c=>c.brandId===user?._id).map(c=>c.id);const scope=user?user.role==="Brand"?{"data.campaignId":{$in:own}}:{"data.creatorId":user._id}:{_id:"never"};const pref=user?await m.preferences.findOne({_id:user._id},options):null;return {brands:(await m.brands.find({},options).limit(1000).toArray()).map(x=>x.data),campaigns:cs,applications:(await m.applications.find(scope,options).limit(1000).toArray()).map(x=>x.data),invitations:(await m.invitations.find(scope,options).limit(1000).toArray()).map(x=>x.data),conversations:user?(await m.conversations.find(user.role==="Brand"?{"data.brandId":user._id}:{"data.creatorId":user._id},options).limit(200).toArray()).map(x=>x.data):[],savedCampaigns:pref?.savedCampaigns||[],savedGroups:pref?.savedGroups||{},activity:user?(await m.activity.find({brandId:user._id},options).sort({time:-1}).limit(100).toArray()).map(x=>({id:x._id,brandId:x.brandId,text:x.text,time:x.time})):[]};}
async function persistRows<T extends {id:string}>(collection:Collection<m.RecordDoc<T>>,before:T[],after:T[],session:ClientSession){const old=new Map(before.map(x=>[x.id,x]));for(const row of after){const previous=old.get(row.id);if(JSON.stringify(previous)===JSON.stringify(row))continue;if(previous)await collection.replaceOne({_id:row.id},{data:row},{session});else await collection.insertOne({_id:row.id,data:row},{session});}}
export const commandSchema=z.object({type:z.enum(["brand.save","campaign.save","campaign.status","campaign.delete","application.submit","application.review","invitation.send","invitation.respond","campaign.saveForCreator","creator.save","creator.organize","message.send"]),id:z.string().max(100).optional(),status:z.string().optional(),input:z.unknown().optional(),group:z.string().max(80).optional(),expected:z.unknown().optional()}).strict();
export type MarketCommand=z.infer<typeof commandSchema>;
export async function marketCommand(user:User,raw:unknown){const command=commandSchema.parse(raw);const actor=actorFor(user);const known=(await listCreators()).map(c=>c!.id);const workspace=user.role==="Creator"?await creatorWorkspace(user):null;const session=client.startSession();try{await session.withTransaction(async()=>{const before=await marketState(user,session);let next=before;const pref=await m.preferences.findOne({_id:user._id},{session});const saved=pref?.savedCreators||[];const input=command.input;const id=command.id||"";
 if(command.expected!==undefined){const current=command.type.startsWith("campaign")?before.campaigns.find(c=>c.id===id):command.type.startsWith("brand")?before.brands.find(b=>b.id===user._id):undefined;if(JSON.stringify(current)!==JSON.stringify(command.expected))throw new ApiError(409,"stale","This record changed. Refresh before saving.");}
 switch(command.type){
 case "brand.save":next=brandService.save(before,actor,brandSchema.parse(input));break;
 case "campaign.save":next=campaignService.save(before,actor,campaignSchema.parse(input));break;
 case "campaign.status":next=campaignService.status(before,actor,id,z.enum(["Draft","Published","Active","Paused","Completed","Archived"]).parse(command.status));break;
 case "campaign.delete":{const c=before.campaigns.find(c=>c.id===id&&c.brandId===user._id);if(user.role!=="Brand"||!c||c.status!=="Draft")throw new ApiError(403,"forbidden","Only your own draft can be deleted.");if(await m.applications.countDocuments({"data.campaignId":id},{session})||await m.invitations.countDocuments({"data.campaignId":id},{session}))throw new ApiError(409,"references","Archive a campaign with applications or invitations instead.");await m.campaigns.deleteOne({_id:id},{session});break;}
 case "application.submit":{const app=applicationSchema.parse(input);if(!workspace)throw new ApiError(403,"forbidden","A Creator account is required.");const creator=ownerCreator(workspace.state);const projects=workspace.state.projects.filter(p=>p.status==="Published"&&app.projects.includes(p.title));if(projects.length!==app.projects.length)throw new ApiError(400,"project","Choose your own published projects.");const pub=workspace.state.publication;if(app.portfolio&&(!pub||pub.portfolio.visibility!=="Public"||app.portfolio!==`/u/${pub.profile.username}`))throw new ApiError(400,"portfolio","Choose your public portfolio.");next=applicationService.submit(before,actor,{...app,creatorId:user._id,demo:false,creatorSnapshot:{id:user._id,name:creator.name,username:creator.username,identity:creator.identity,skills:creator.skills,category:creator.category,categories:creator.categories||[],projects:projects.map(p=>({name:p.title,detail:[p.description,...p.techStack].join(" ")})),publicPortfolio:!!app.portfolio}});break;}
 case "application.review":next=applicationService.review(before,actor,id,z.enum(["Pending","Shortlisted","Accepted","Rejected","Withdrawn"]).parse(command.status));break;
 case "invitation.send":next=invitationService.send(before,actor,invitationSchema.parse(input),known);break;
 case "invitation.respond":next=invitationService.respond(before,actor,id,z.enum(["Pending","Accepted","Declined","Cancelled"]).parse(command.status));break;
 case "campaign.saveForCreator":next=campaignService.saveForCreator(before,actor,id);break;
 case "creator.organize":next=savedCreatorService.organize(before,actor,id,command.group||"",saved);break;
 case "message.send":{const body=z.object({campaignId:z.string(),creatorId:z.string(),text:z.string().min(1).max(6000)}).strict().parse(input);const c=before.campaigns.find(c=>c.id===body.campaignId);if(!c)throw new ApiError(404,"not_found","Campaign not found.");const allowed=[...known,...before.applications.filter(a=>a.campaignId===c.id).map(a=>a.creatorId)];next=messageService.send(before,actor,{brandId:c.brandId,creatorId:body.creatorId,campaignId:c.id},body.text,allowed);break;}
 case "creator.save":if(!known.includes(id))throw new ApiError(404,"not_found","Creator is not publicly available.");await m.preferences.updateOne({_id:user._id},{$set:{savedCreators:toggleSaved(saved,id)},$setOnInsert:{savedCampaigns:[],savedGroups:{}}},{upsert:true,session});break;
 }
 await persistRows(m.brands,before.brands,next.brands,session);await persistRows(m.campaigns,before.campaigns,next.campaigns,session);await persistRows(m.applications,before.applications,next.applications,session);await persistRows(m.invitations,before.invitations,next.invitations,session);await persistRows(m.conversations,before.conversations,next.conversations,session);await notifyChanges(before,next,user._id,session);
 if(command.type==="campaign.saveForCreator"||command.type==="creator.organize")await m.preferences.updateOne({_id:user._id},{$set:{savedCampaigns:next.savedCampaigns,savedGroups:next.savedGroups},$setOnInsert:{savedCreators:[]}},{upsert:true,session});
 for(const a of next.activity.filter(x=>!before.activity.some(b=>b.id===x.id)))await m.activity.insertOne({_id:a.id,brandId:a.brandId,text:a.text,time:a.time},{session});
 });return await marketState(user);}catch(e){if(e instanceof ApiError||e instanceof z.ZodError||(e as {code?:number}).code===11000)throw e;throw new ApiError(400,"invalid_operation",e instanceof Error?e.message:"The operation could not be completed.");}finally{await session.endSession();}}
